import React,{useEffect,useState} from 'react';
import { Check, Clock3, ShieldCheck, Users, BookOpen, X, BarChart3 } from 'lucide-react';
import { API } from '../api';
import { useStatus } from '../components/StatusProvider';

export default function Admin(){
 const status=useStatus(); const [data,setData]=useState({pendingCourses:[],notifications:[],counts:{}}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);try{const r=await API.get('/admin/overview');setData(r.data);}catch(e){status.error('Admin data failed',e.response?.data?.message||'Could not load review queue.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const review=async(id,decision)=>{setBusy(id+decision);try{let reason='';if(decision==='rejected'){reason=window.prompt('Reason for rejection:','Please improve the course description, lesson structure, or learning outcomes.')||'';}await API.post(`/admin/courses/${id}/review`,{decision,reason});status.success(decision==='approved'?'Course approved':'Course rejected',decision==='approved'?'The course is now live.':'The instructor has been notified.');await load();}catch(e){status.error('Review failed',e.response?.data?.message||'Could not update the course.');}finally{setBusy('');}};
 const markRead=async()=>{try{await API.post('/admin/notifications/read');await load();}catch{}};
 const c=data.counts;
 return <div className="page"><div className="container admin-page"><div className="dash-head"><div><div className="eyebrow">ADMIN CONTROL CENTER</div><h1>Review the classroom.</h1><p>Manage the Learny marketplace and approve instructor submissions.</p></div><div className="dash-stat"><ShieldCheck/><span><b>{c.pendingCourses||0}</b><small>Pending</small></span></div></div>
 <div className="admin-stats"><div><Users/><b>{c.students||0}</b><span>Students</span></div><div><Users/><b>{c.instructors||0}</b><span>Instructors</span></div><div><BookOpen/><b>{c.courses||0}</b><span>Total courses</span></div><div><BarChart3/><b>{c.approvedCourses||0}</b><span>Published</span></div></div>
 <div className="admin-grid"><section className="studio-card"><div className="section-head"><div><div className="eyebrow">COURSE APPROVALS</div><h2>Pending submissions</h2></div><span className="status-pill loading-pill"><Clock3 size={14}/> Review required</span></div>{loading?<div className="state-card loading-state"><span className="loader yellow"/><b>Loading review queue...</b></div>:data.pendingCourses.length?data.pendingCourses.map(course=><article className="review-card" key={course._id}><div className="review-thumb">{course.thumbnail?<img src={course.thumbnail} alt=""/>:<span>{course.title.charAt(0)}</span>}</div><div className="review-body"><div className="eyebrow">{course.category} · {course.level}</div><h3>{course.title}</h3><p>{course.description}</p><div className="review-meta"><span>By <b>{course.instructor?.name}</b></span><span>{course.lessons.length} lessons</span><span>{course.price?`₦${course.price.toLocaleString()}`:'Free'}</span></div><div className="review-actions"><button className="btn success-btn" disabled={busy===course._id+'approved'} onClick={()=>review(course._id,'approved')}><Check size={16}/> Approve</button><button className="btn danger-btn" disabled={busy===course._id+'rejected'} onClick={()=>review(course._id,'rejected')}><X size={16}/> Reject</button></div></div></article>):<div className="state-card compact"><ShieldCheck/><h3>Nothing waiting for approval.</h3><p>New instructor submissions will appear here.</p></div>}</section>
 <aside className="studio-card notifications-card"><div className="section-head"><div><div className="eyebrow">NOTIFICATIONS</div><h2>Activity</h2></div>{data.counts.unread>0&&<button className="text-button" onClick={markRead}>Mark read</button>}</div>{data.notifications.length?data.notifications.map(n=><div className={`notification-row ${n.read?'':'unread'}`} key={n._id}><span className="notification-dot"/><div><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div></div>):<p className="muted">No notifications yet.</p>}</aside></div></div></div>;
}
