import React,{useEffect,useState} from 'react';
import { Search,SlidersHorizontal,Sparkles,Star } from 'lucide-react';
import { API } from '../api';
import CourseCard from '../components/CourseCard';
import ExternalCourseCard from '../components/ExternalCourseCard';
import { externalCourses } from '../data/externalCourses';
const cats=['All','Development','Design','Productivity','Business'];
export default function Courses(){
 const [courses,setCourses]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[level,setLevel]=useState('All'),[sort,setSort]=useState('newest'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);API.get('/courses',{params:{search,category,level,sort}}).then(r=>alive&&setCourses(r.data.courses)).catch(e=>alive&&setError(e.response?.data?.message||'Could not load courses.')).finally(()=>alive&&setLoading(false));return()=>{alive=false;};},[search,category,level,sort]);
 return <div className="page"><div className="container"><div className="page-hero"><div><div className="pill"><Sparkles size={14}/> Learn at your own pace</div><h1>Explore the library.</h1><p>Practical courses for developers, designers, creators and curious minds.</p></div><div className="search-box"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search courses..."/></div></div><div className="filter-row"><SlidersHorizontal size={17}/>{cats.map(c=><button className={category===c?'filter active':'filter'} key={c} onClick={()=>setCategory(c)}>{c}</button>)}<select className="filter-select" value={level} onChange={e=>setLevel(e.target.value)}><option value="All">All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select className="filter-select" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="rating">Top rated</option><option value="priceLow">Price: low</option><option value="priceHigh">Price: high</option></select></div>{error?<div className="state-card error-state"><h3>Could not load courses</h3><p>{error}</p></div>:loading?<div className="state-card loading-state"><span className="loader yellow"/><b>Loading courses...</b></div>:courses.length?<div className="course-grid">{courses.map((c,i)=><CourseCard key={c._id} course={c} index={i}/>)}</div>:<div className="state-card"><h3>No courses found</h3><p>Try another search or filter.</p></div>}</div><section className="external-library"><div className="section-head"><div><div className="eyebrow">CURATED EXTERNAL LEARNING</div><h2>More courses from Udemy</h2><p>These stay on Udemy. Learny links to the original course page instead of copying third-party course content.</p></div><Star size={18}/></div><div className="external-course-grid">{externalCourses.map((course,i)=><ExternalCourseCard key={course.url} course={course} index={i}/>)}</div></section></div>;
}
