import React,{useEffect,useState} from 'react';
import { ArrowLeft, CheckCircle2, Clock3, LockKeyhole, PlayCircle, ShieldCheck, Sparkles, Star } from 'lucide-react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { API } from '../api';
import { useAuth } from '../context';
import { useStatus } from '../components/StatusProvider';
import { getCourseImage } from '../utils/courseImages';

export default function CourseDetail(){
 const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();const status=useStatus();const [data,setData]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [rating,setRating]=useState(5);const [comment,setComment]=useState('');
 useEffect(()=>{API.get(`/courses/${id}`).then(r=>setData(r.data)).catch(e=>setError(e.response?.data?.message||'Course not found.'));},[id]);
 if(error)return <div className="state-card page"><h2>{error}</h2><Link className="btn ghost" to="/courses">Back to courses</Link></div>;
 if(!data)return <div className="screen-loader"><span className="loader yellow"/><b>Loading course...</b></div>;
 const {course,enrolled,reviews=[]}=data;const total=course.lessons.reduce((s,l)=>s+(l.duration||0),0);
 const enroll=async()=>{if(!user){navigate('/login',{state:{from:`/courses/${id}`}});return;}if(user.activeRole!=='student'){status.error('Switch to Student mode','Only students can enroll in courses.');return;}setBusy(true);try{await API.post(`/courses/${id}/enroll`);setData(d=>({...d,enrolled:true}));status.success('Enrollment complete','Your lessons are now unlocked.');}catch(e){status.error('Enrollment failed',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 const submitReview=async e=>{e.preventDefault();setBusy(true);try{const r=await API.post(`/courses/${id}/reviews`,{rating,comment});status.success('Review saved','Thanks for helping other learners.');setData(d=>({...d,course:{...d.course,ratingAverage:r.data.ratingAverage,reviewCount:r.data.reviewCount},reviews:[...d.reviews.filter(x=>x.student?._id!==user?.id),{student:{name:user.name},rating,comment}]}));setComment('');}catch(e){status.error('Review failed',e.response?.data?.message||'Complete the course before reviewing.');}finally{setBusy(false);}};
 return <div className="page"><div className="container detail"><Link to="/courses" className="back"><ArrowLeft size={16}/> Back to courses</Link><div className="detail-grid"><div><div className="detail-cover"><img src={getCourseImage(course)} alt={`${course.title} course thumbnail`} onError={e=>{e.currentTarget.src='/course-images/development.svg';}}/><div className="detail-cover-label"><Sparkles size={14}/> {course.category}</div></div><div className="detail-copy"><div className="eyebrow">{course.category} · {course.level}</div><h1>{course.title}</h1><p>{course.description}</p><div className="byline">Created by <b>{course.instructor?.name}</b> · {course.lessons.length} lessons · {total} min · <Star size={14} fill="currentColor"/> {course.ratingAverage||'New'} ({course.reviewCount||0})</div></div></div><aside className="enroll-card"><div className="enroll-top">{course.isPremium?<span className="premium-tag"><LockKeyhole size={13}/> Premium</span>:<span className="free-tag"><Sparkles size={13}/> Free</span>}<span className="price-lg">{course.price?`₦${course.price.toLocaleString()}`:'Free'}</span></div><h3>{enrolled?'You are enrolled.':'Ready to start?'}</h3><p>{enrolled?'Your lessons are unlocked. Continue where you left off.':'Enroll to unlock the full lesson path and track your progress.'}</p>{enrolled?<Link className="btn primary full" to={course.lessons[0]?`/courses/${id}/lesson/${course.lessons[0]._id}`:'#'}>Start learning <PlayCircle size={17}/></Link>:user?.activeRole==='admin'?<div className="secure-note"><ShieldCheck size={15}/> Admin accounts cannot enroll.</div>:<button className="btn primary full" onClick={enroll} disabled={busy}>{busy?'Enrolling...':'Enroll now'} <ArrowLeft className="rotate" size={17}/></button>}<div className="secure-note"><ShieldCheck size={15}/> Authenticated access & progress tracking</div></aside></div><section className="lesson-list"><div className="section-head"><div><div className="eyebrow">COURSE CONTENT</div><h2>Inside the course</h2></div>{enrolled&&<span className="success"><CheckCircle2 size={15}/> Enrolled</span>}</div>{course.lessons.map((lesson,i)=><div className="lesson-row" key={lesson._id}><div className="lesson-num">{String(i+1).padStart(2,'0')}</div><div className="lesson-info"><b>{lesson.title}</b><span>{lesson.description}</span></div><div className="lesson-right">{lesson.isPreview||enrolled?<Link to={`/courses/${id}/lesson/${lesson._id}`}><PlayCircle size={18}/></Link>:<LockKeyhole size={17}/>}<span><Clock3 size={14}/>{lesson.duration} min</span></div></div>)}</section>
 <section className="reviews-section"><div className="section-head"><div><div className="eyebrow">LEARNER FEEDBACK</div><h2>Ratings & reviews</h2></div><strong className="rating-big"><Star size={18} fill="currentColor"/> {course.ratingAverage||'New'}</strong></div>{enrolled&&user?.activeRole==='student'&&<form className="review-form" onSubmit={submitReview}><div className="star-picker">{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=rating?'star active':'star'} onClick={()=>setRating(n)}><Star size={22} fill="currentColor"/></button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="What did you think of the course?" maxLength={500}/><button className="btn primary" disabled={busy}>Submit review</button></form>}<div className="review-list">{reviews.length?reviews.map((r,i)=><article className="review-item" key={r._id||i}><div><b>{r.student?.name||'Learner'}</b><span className="review-stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span></div><p>{r.comment||'Completed this course.'}</p></article>):<p className="muted">No reviews yet. Complete the course to leave the first one.</p>}</div></section>
 </div></div>;
}
