import React,{useEffect,useState} from 'react';
import { ArrowRight,BookOpen,CheckCircle2,GraduationCap,Sparkles,Trophy } from 'lucide-react';
import { Link,useNavigate } from 'react-router-dom';
import { API } from '../api';
import { useAuth } from '../context';
import { useStatus } from '../components/StatusProvider';
import CourseCard from '../components/CourseCard';
import ProgressBar from '../components/ProgressBar';
import { getCourseImage } from '../utils/courseImages';
export default function Dashboard(){
 const {user,becomeInstructor}=useAuth();const status=useStatus();const [learning,setLearning]=useState([]);const [stats,setStats]=useState({});const [busy,setBusy]=useState(false);const navigate=useNavigate();
 useEffect(()=>{API.get('/my/learning').then(r=>{setLearning(r.data.learning);setStats(r.data.stats||{});}).catch(()=>{});},[]);
 const active=learning.find(x=>x.percentage<100)||learning[0];
 const enableTeaching=async()=>{setBusy(true);try{await becomeInstructor();status.success('Instructor mode ready','You can now build courses.');navigate('/instructor');}catch(e){status.error('Could not enable teaching',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 return <div className="page"><div className="container dashboard"><div className="dash-head"><div><div className="eyebrow">YOUR LEARNING SPACE</div><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Keep your momentum going. A little progress compounds.</p></div><div className="dash-stat"><BookOpen/><span><b>{stats.total||0}</b><small>Courses</small></span></div></div><div className="learning-stats"><div><GraduationCap/><b>{stats.inProgress||0}</b><span>In progress</span></div><div><Trophy/><b>{stats.completed||0}</b><span>Completed</span></div><div><CheckCircle2/><b>{stats.total?Math.round(learning.reduce((s,x)=>s+x.percentage,0)/stats.total):0}%</b><span>Average progress</span></div></div>{user.roles?.length===1&&user.roles[0]==='student'&&<section className="studio-card become-banner"><div><div className="eyebrow">TEACH ON LEARNY</div><h2>Turn what you know into a course.</h2><p>Add instructor capability to this same account and switch between learning and teaching.</p></div><button className="btn primary" disabled={busy} onClick={enableTeaching}>{busy?'Opening...':'Become an instructor'} <ArrowRight size={16}/></button></section>}{active&&<section className="continue-card"><div className="continue-cover"><img src={getCourseImage(active.course)} alt=""/></div><div className="continue-content"><div className="eyebrow">CONTINUE LEARNING</div><h2>{active.course.title}</h2><p>{active.course.lessons.length} lessons · {active.course.instructor?.name}</p><ProgressBar value={active.percentage}/><div className="continue-foot"><span><b>{active.percentage}%</b> complete</span>{active.percentage===100?<span className="success"><Trophy size={16}/> Completed</span>:<Link className="btn primary" to={`/courses/${active.course._id}/lesson/${active.course.lessons[0]?._id}`}>Continue <ArrowRight size={16}/></Link>}</div></div></section>}<div className="section-head"><div><div className="eyebrow">MY LIBRARY</div><h2>Enrolled courses</h2></div><span className="muted"><CheckCircle2 size={15}/> {stats.completed||0} completed</span></div>{learning.length?<div className="course-grid">{learning.map((x,i)=><div className="learning-card-wrap" key={x.id}><CourseCard course={x.course} index={i} progress={x.percentage}/>{x.percentage===100&&<Link className="certificate-link" to={`/courses/${x.course._id}/certificate`}><Trophy size={14}/> View certificate</Link>}</div>)}</div>:<div className="state-card"><Sparkles/><h3>Your library is waiting.</h3><p>Explore a course and enroll to see it here.</p><Link className="btn primary" to="/courses">Explore courses</Link></div>}</div></div>;
}
