import React,{useEffect,useMemo,useState} from 'react';
import { BookOpen, BookPlus, CheckCircle2, CreditCard, LockKeyhole, Plus, ShieldCheck, Trash2, Video, Pencil, Send } from 'lucide-react';
import { API } from '../api';
import { useAuth } from '../context';
import { useStatus } from '../components/StatusProvider';

const blankCourse={title:'',description:'',category:'Development',level:'Beginner',price:0,isPremium:false,thumbnail:''};
const blankLesson={title:'',description:'',videoUrl:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',duration:8,isPreview:false};
export default function Instructor(){
 const {user,refresh}=useAuth(); const status=useStatus(); const [access,setAccess]=useState(user?.instructorAccess); const [courses,setCourses]=useState([]); const [selected,setSelected]=useState(null); const [busy,setBusy]=useState(false); const [form,setForm]=useState(blankCourse); const [lesson,setLesson]=useState(blankLesson); const [editing,setEditing]=useState(false);
 const load=async()=>{const [s,c]=await Promise.all([API.get('/instructor/status'),API.get('/instructor/courses')]);setAccess(s.data.access);setCourses(c.data.courses);setSelected(prev=>prev?c.data.courses.find(x=>x._id===prev._id)||prev:null);};
 useEffect(()=>{load().catch(e=>status.error('Studio unavailable',e.response?.data?.message||'Could not load instructor data.'));},[]);
 useEffect(()=>{const ref=new URLSearchParams(window.location.search).get('payment');if(ref){API.post(`/instructor/payment/paystack/verify/${ref}`).then(r=>{setAccess(r.data.access);refresh();status.success('Payment verified','Instructor publishing access is now active.');window.history.replaceState({},'',window.location.pathname);load();}).catch(e=>status.error('Payment not verified',e.response?.data?.message||'Payment could not be verified.'));}},[]);
 const activate=async plan=>{setBusy(true);try{const r=await API.post('/instructor/activate',{plan});setAccess(r.data.access);await refresh();status.success('Publishing access active','Development activation enabled. Connect Paystack/Flutterwave before production.');}catch(e){status.error('Activation failed',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 const pay=async plan=>{setBusy(true);try{const r=await API.post('/instructor/payment/paystack/initialize',{plan});window.location.href=r.data.authorization_url;}catch(e){status.error('Payment unavailable',e.response?.data?.message||'Configure PAYSTACK_SECRET_KEY first.');}finally{setBusy(false);}};
 const create=async e=>{e.preventDefault();setBusy(true);try{const r=await API.post('/instructor/courses',form);setCourses(p=>[r.data.course,...p]);setSelected(r.data.course);setForm(blankCourse);status.success('Course created','Your course is awaiting admin review.');}catch(e){status.error('Course creation failed',e.response?.data?.message||'Check the form.');}finally{setBusy(false);}};
 const save=async e=>{e.preventDefault();setBusy(true);try{const r=await API.patch(`/instructor/courses/${selected._id}`,form);setSelected(r.data.course);setCourses(p=>p.map(c=>c._id===r.data.course._id?r.data.course:c));setEditing(false);status.success('Course updated','The updated course is awaiting admin review.');}catch(e){status.error('Update failed',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 const add=async e=>{e.preventDefault();if(!selected)return;setBusy(true);try{const r=await API.post(`/instructor/courses/${selected._id}/lessons`,lesson);setSelected(r.data.course);setCourses(p=>p.map(c=>c._id===r.data.course._id?r.data.course:c));setLesson(blankLesson);status.success('Lesson added','The course has been sent back for review if necessary.');}catch(e){status.error('Lesson creation failed',e.response?.data?.message||'Check the lesson details.');}finally{setBusy(false);}};
 const remove=async()=>{if(!selected||!window.confirm('Delete this course permanently?'))return;setBusy(true);try{await API.delete(`/instructor/courses/${selected._id}`);setCourses(p=>p.filter(c=>c._id!==selected._id));setSelected(null);status.success('Course deleted','The course has been removed.');}catch(e){status.error('Delete failed',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 const resubmit=async()=>{if(!selected)return;setBusy(true);try{const r=await API.post(`/instructor/courses/${selected._id}/resubmit`);setSelected(r.data.course);setCourses(p=>p.map(c=>c._id===selected._id?r.data.course:c));status.success('Course resubmitted','Admin has been notified.');}catch(e){status.error('Resubmission failed',e.response?.data?.message||'Please try again.');}finally{setBusy(false);}};
 const active=access?.status==='active'&&(!access.expiresAt||new Date(access.expiresAt)>new Date()); const totalLessons=useMemo(()=>courses.reduce((s,c)=>s+(c.lessons?.length||0),0),[courses]);
 return <div className="page"><div className="container instructor"><div className="dash-head"><div><div className="eyebrow">INSTRUCTOR STUDIO</div><h1>Build your classroom.</h1><p>Create, refine and submit courses for admin review.</p></div><div className="studio-stats"><span><b>{courses.length}</b><small>Courses</small></span><span><b>{totalLessons}</b><small>Lessons</small></span></div></div>
 {!active?<section className="studio-card paywall-card"><div className="paywall-icon"><CreditCard/></div><div><div className="eyebrow">INSTRUCTOR ACCESS</div><h2>Unlock course publishing.</h2><p>Development gate is active. Real Paystack/Flutterwave checkout requires your merchant credentials before production.</p><div className="plan-grid"><div className="plan-card"><span>Monthly</span><strong>₦2,500</strong><small>30 days publishing access</small><button className="btn primary full" onClick={()=>pay('monthly')} disabled={busy}>{busy?'Opening...':'Pay with Paystack'}</button><button className="btn ghost full" onClick={()=>activate('monthly')} disabled={busy}>Use test activation</button></div><div className="plan-card featured"><span>Annual</span><strong>₦20,000</strong><small>365 days publishing access</small><button className="btn mint full" onClick={()=>pay('annual')} disabled={busy}>{busy?'Opening...':'Pay with Paystack'}</button><button className="btn ghost full" onClick={()=>activate('annual')} disabled={busy}>Use test activation</button></div></div><div className="secure-note"><ShieldCheck size={15}/> Server-side instructor permission protection.</div></div></section>:<><div className="studio-toolbar"><div><div className="eyebrow">YOUR COURSES</div><h2>Course studio</h2></div><button className="btn primary" onClick={()=>{setSelected(null);setForm(blankCourse);setEditing(false);}}><Plus size={17}/> New course</button></div>
 <div className="instructor-grid"><section className="studio-card course-list-panel"><div className="section-head"><div><h2>My courses</h2><p>{courses.length} course{courses.length===1?'':'s'}.</p></div></div>{courses.length?courses.map((c,i)=><button key={c._id} className={`instructor-course-row ${selected?._id===c._id?'selected':''}`} onClick={()=>{setSelected(c);setEditing(false);}}><span className="course-row-number">{String(i+1).padStart(2,'0')}</span><span><b>{c.title}</b><small>{c.category} · {c.lessons.length} lessons · <b className={`course-status ${c.status}`}>{c.status}</b></small></span><strong>{c.price?`₦${c.price.toLocaleString()}`:'Free'}</strong></button>):<div className="state-card compact"><BookOpen/><h3>No courses yet</h3><p>Create your first course.</p></div>}</section>
 {!selected?<CourseForm form={form} setForm={setForm} onSubmit={create} busy={busy} title="Create a course" submit="Create course"/>:<section className="studio-card studio-form">{editing?<CourseFields form={form} setForm={setForm}/>:<><div className="selected-course-head"><div><div className="eyebrow">COURSE BUILDER</div><h2>{selected.title}</h2><p>{selected.lessons.length} lessons · {selected.isPremium?'Premium':'Free'}</p></div><span className={`published-badge ${selected.status}`}><CheckCircle2 size={14}/> {selected.status==='approved'?'Published':selected.status==='rejected'?'Needs changes':'Awaiting admin review'}</span></div>{selected.status==='rejected'&&<div className="rejection-box"><b>Admin feedback</b><p>{selected.rejectionReason||'Please improve the course and resubmit.'}</p><button className="btn primary" onClick={()=>{setForm({...selected});setEditing(true);}}>Edit course</button></div>}
 <div className="builder-actions"><button className="btn ghost" onClick={()=>{setForm({...selected});setEditing(true);}}><Pencil size={16}/> Edit</button><button className="btn danger-btn" onClick={remove} disabled={busy}><Trash2 size={16}/> Delete</button>{selected.status==='rejected'&&<button className="btn primary" onClick={resubmit} disabled={busy}><Send size={16}/> Resubmit</button>}</div></>}{editing&&<button className="btn primary full" onClick={save} disabled={busy}>{busy?'Saving...':'Save changes & submit for review'}</button>}
 <div className="lesson-builder"><div className="lesson-builder-title"><Video size={18}/><div><b>Add a lesson</b><small>Hosted MP4/video URL for this MVP.</small></div></div><form onSubmit={add}><label>Lesson title<input required value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})}/></label><label>Description<textarea rows="3" value={lesson.description} onChange={e=>setLesson({...lesson,description:e.target.value})}/></label><label>Video URL<input required type="url" value={lesson.videoUrl} onChange={e=>setLesson({...lesson,videoUrl:e.target.value})}/></label><div className="two-col"><label>Duration<input type="number" min="1" value={lesson.duration} onChange={e=>setLesson({...lesson,duration:Number(e.target.value)})}/></label><label className="check-line compact-check"><input type="checkbox" checked={lesson.isPreview} onChange={e=>setLesson({...lesson,isPreview:e.target.checked})}/><span><b>Free preview</b><small>Allow preview without enrollment.</small></span></label></div><button className="btn primary full" disabled={busy}>{busy?'Adding...':'Add lesson'} <Plus size={17}/></button></form></div><div className="lesson-outline"><div className="eyebrow">LESSON OUTLINE</div>{selected.lessons.length?selected.lessons.map((l,i)=><div className="outline-row" key={l._id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{l.title}</b><small>{l.duration} min · {l.isPreview?'Preview':'Protected'}</small></div><LockKeyhole size={15}/></div>):<p className="muted">Add your first lesson.</p>}</div></section>}</div></>}</div></div>;
}
function CourseFields({form,setForm}){return <><label>Course title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two-col"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Development</option><option>Design</option><option>Productivity</option><option>Business</option></select></label><label>Level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label></div><div className="two-col"><label>Price (₦)<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Thumbnail URL<input value={form.thumbnail||''} onChange={e=>setForm({...form,thumbnail:e.target.value})}/></label></div><label className="check-line"><input type="checkbox" checked={!!form.isPremium} onChange={e=>setForm({...form,isPremium:e.target.checked})}/><span><b>Premium course</b><small>Require enrollment for protected lessons.</small></span></label></>}
function CourseForm({form,setForm,onSubmit,busy,title,submit}){return <form className="studio-card studio-form" onSubmit={onSubmit}><div className="section-head"><div><div className="eyebrow">NEW COURSE</div><h2>{title}</h2><p>Start with a clear promise of what students will achieve.</p></div></div><CourseFields form={form} setForm={setForm}/><button className="btn primary full" disabled={busy}>{busy?'Saving...':submit}<BookPlus size={17}/></button></form>}
