import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, PlayCircle, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { API } from '../api';
import { useStatus } from '../components/StatusProvider';

export default function Lesson() {
  const { id, lessonId } = useParams(); const status = useStatus(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { API.get(`/courses/${id}/lessons/${lessonId}`).then(r => setData(r.data)).catch(e => setError(e.response?.data?.message || 'Lesson could not be opened.')); }, [id, lessonId]);
  if (error) return <div className="state-card page"><h2>{error}</h2><Link className="btn ghost" to={`/courses/${id}`}>Back to course</Link></div>;
  if (!data) return <div className="screen-loader"><span className="loader yellow"/><b>Loading lesson...</b></div>;
  const complete = async () => { setSaving(true); status.loading(data.completed ? 'Updating progress' : 'Saving progress', data.completed ? 'Updating your lesson status...' : 'Marking this lesson complete...'); try { const r = await API.patch(`/courses/${id}/lessons/${lessonId}/progress`, { completed: !data.completed }); setData(d => ({...d, completed: !d.completed, progress: r.data})); status.success(data.completed ? 'Progress updated' : 'Lesson completed', data.completed ? 'Your completion status was updated.' : 'Nice work. Your course progress has been saved.'); } catch (e) { status.error('Progress update failed', e.response?.data?.message || 'Please try again.'); } finally { setSaving(false); } };
  return <div className="lesson-page"><div className="container"><Link to={`/courses/${id}`} className="back"><ArrowLeft size={16}/> Course overview</Link><div className="lesson-layout"><aside className="lesson-sidebar"><div className="eyebrow">NOW LEARNING</div><h3>{data.course.title}</h3><div className="lesson-nav"><div className="current"><span>01</span><b>{data.lesson.title}</b></div></div><div className="sidebar-note"><ShieldCheck size={16}/><span>Protected lesson access</span></div></aside><section className="lesson-main"><div className="video-shell"><video controls src={data.lesson.videoUrl}><track kind="captions" /></video><div className="video-fallback"><PlayCircle size={36}/></div></div><div className="lesson-heading"><div><div className="eyebrow">LESSON</div><h1>{data.lesson.title}</h1><p>{data.lesson.description}</p></div><button className={data.completed ? 'btn success-btn' : 'btn primary'} onClick={complete} disabled={saving}>{data.completed ? <><CheckCircle2 size={17}/> Completed</> : saving ? 'Saving...' : <><CheckCircle2 size={17}/> Mark complete</>}</button></div><div className="lesson-bottom"><Link to={`/courses/${id}`}><ChevronLeft/> Back to course</Link><span>{data.lesson.duration} min lesson</span><Link to={`/courses/${id}`} >Course outline <ChevronRight/></Link></div></section></div></div></div>;
}
